import {
  donfackDylane,
  kanjoElkamira,
  macBrenda,
  sakaMercy,
  chestlyAce,
} from '@/lib/images'
import type { TeamMember } from '@/components/TeamCard'

export const teamMembers: TeamMember[] = [
  {
    id: 'donfack-dylane',
    name: 'DONFACK TSOPFACT YVES DYLANE',
    role: 'Lead Developer',
    image: donfackDylane,
    linkedin: '#',
    github: '#',
    twitter: '#',
    instagram: '#',
  },
  {
    id: 'kanjo-elkamira',
    name: 'KANJO ELKAMIRA NDI',
    role: 'QA Engineer',
    image: kanjoElkamira,
    linkedin: '#',
    github: '#',
    twitter: '#',
    instagram: '#',
  },
  {
    id: 'mac-brenda',
    name: 'ENOW EWEH MAC BRENDA',
    role: 'Developer',
    image: macBrenda,
    linkedin: '#',
    github: '#',
    twitter: '#',
    instagram: '#',
  },
  {
    id: 'sacka-mercy',
    name: 'SACKA MERCY',
    role: 'Product Designer',
    image: sakaMercy,
    linkedin: '#',
    github: '#',
    twitter: '#',
    instagram: '#',
  },
  {
    id: 'chestly-amahndong',
    name: 'CHESTLY AMAHNDONG',
    role: 'Developer',
    image: chestlyAce,
    linkedin: '#',
    github: '#',
    twitter: '#',
    instagram: '#',
  },
]
